[model]

# cycle:
#
# 这是预加载的时间量子。预加载每隔一个周期执行一次数据收集和预测。
# 请使用偶数。
#
# 注意：将此参数设置得太低可能会降低系统性能和稳定性。
#
# 单位：秒
# 默认值：20
#
cycle = 20

# usecorrelation:
#
# 是否在预测算法中使用相关系数。关于是否使用它，存在支持和反对的论据。
# 目前认为使用它可以获得更准确的预测。该选项将来可能会被移除。
#
# 默认值：true
usecorrelation = true

# minsize:
#
# 预加载考虑跟踪应用程序所需的最小进程内存映射总长度。
#
# 注意：将此参数设置得太高会降低预加载的效果，而设置得太低则会因为跟踪
# 更多进程而导致资源消耗呈平方级增长。
#
# 单位：字节
# 默认值：2000000
#
minsize = 2000000

#
# 以下参数控制每个周期内预加载允许用于预加载的内存量。所有值均为百分比，
# 并限制在 -100 到 100 之间。
#
# 预加载用于预取的总内存随后使用以下公式计算：
#
# 	max (0, TOTAL * memtotal + FREE * memfree) + CACHED * memcached
# 其中 TOTAL、FREE 和 CACHED 是在运行时从 /proc/meminfo 读取的相应值。
#

# memtotal: 占总内存的百分比
#
# 单位：有符号整数百分比
# 默认值：-10
#
memtotal = -10

# memfree: 占空闲内存的百分比
#
# 单位：有符号整数百分比
# 默认值：50
#
memfree = 50

# memcached: 占缓存内存的百分比
#
# 单位：有符号整数百分比
# 默认值：0
#
memcached = 0


###########################################################################

[system]

# doscan:
#
# 是否预加载应监控运行中的进程并更新其模型状态。通常你需要这样做，
# 这正是预加载的作用，但你可能出于各种原因（如测试，仅进行预测）暂时
# 关闭它。请注意，如果扫描关闭，则预测将仅基于预加载启动时运行过的
# 进程进行，并且运行中的进程列表根本不会更新。
#
# 默认值：true
doscan = true

# dopredict:
#
# 是否预加载应进行预测并从磁盘预取任何数据。与 doscan 非常相似，通常
# 你需要这样做，这是预加载的另一半功能，但你可能希望暂时关闭它，例如
# 仅训练模型。请注意，这允许你通过修改配置文件并向守护进程发送信号，
# 动态地打开或关闭扫描/预测功能。
#
# 默认值：true
dopredict = true

# autosave:
#
# 预加载将每隔 autosave 周期自动将状态保存到磁盘。这仅在 doscan 设置
# 为 true 时相关。请注意，对模型的某些维护工作，例如删除不再存在的
# 文件的条目，会在状态保存时进行。因此，不建议完全关闭自动保存。
#
# 单位：秒
# 默认值：3600
#
autosave = 3600

# mapprefix:
#
# 一个路径前缀列表，用于控制哪些映射文件将被预加载考虑，哪些不被考虑。
# 列表项由分号分隔。一旦匹配到第一个项目，匹配过程即停止。对于每个项目，
# 如果该项目出现在文件路径的开头，则匹配成功，该文件被接受。另一方面，
# 如果项目以感叹号作为其第一个字符，则考虑该项目的其余部分，如果匹配成功，
# 则该文件被拒绝。例如，值 "!/lib/modules;/" 意味着除了 /lib/modules 中的
# 文件外，所有其他文件都应被接受。在这种情况下，尾部的项目可以移除，
# 因为如果没有匹配发生，文件是被接受的。建议确保 /dev 被拒绝，因为预加载
# 内部不特殊处理设备文件。
#
# 注意：/lib 会匹配所有的 /lib、/lib64，甚至如果有 /libexec 也会匹配。
# 如果某人确实只想要 /lib，他们应该使用 /lib/。
#
# 默认值：（空列表，接受所有）
mapprefix = /usr/;/lib;/var/cache/;!/

# exeprefix:
#
# 该语法与 mapprefix 完全相同。唯一的区别是，此设置用于接受或拒绝二进制
# 可执行文件，而不是映射文件。
#
# 默认值：（空列表，接受所有）
exeprefix = !/usr/sbin/;!/usr/local/sbin/;/usr/;!/

# maxprocs
#
# 用于执行并行预读的最大进程数。如果等于 0，则不进行并行处理，所有预读
# 都在进程内完成。并行预读据称能提供更好的 I/O 性能，因为它允许内核将
# 多个相邻块的 I/O 请求进行批处理。
#
# 默认值：30
processes = 30

# sortstrategy
#
# I/O 排序策略。理想情况下，这应该自动决定，但目前并非如此。可选值：
#
#   0 -- SORT_NONE:   不进行 I/O 排序。
#                      例如在闪存上有用。
#   1 -- SORT_PATH:   仅基于文件路径排序。
#                      适用于网络文件系统。
#   2 -- SORT_INODE:  基于 inode 编号排序。
#                      比下一个选项执行更少的维护性 I/O。
#   3 -- SORT_BLOCK:  基于磁盘块进行 I/O 排序。最复杂。
#                      并且适用于大多数 Linux 文件系统。
#
# 默认值：3
sortstrategy = 3
